package HashTable;
import java.util.*;

/**
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 *      Input:
 *      s = "abcd"
 *      t = "abcde"
 *      Output:
 *      e
 * Explanation:
 *      'e' is the letter that was added.
 */
class Solution389 {
    /**
     * Runtime: 7 ms, faster than 22.75% of Java online submissions for Find the Difference.
     * Memory Usage: 37 MB, less than 90.34% of Java online submissions for Find the Difference.
     */
    public char findTheDifference(String s, String t) {
        Map<Character , Integer> map = new HashMap<Character, Integer>();
        for(char c : s.toCharArray()) {
            if(map.containsKey(c)) map.put(c , map.get(c) +1 );
            else map.put(c , 1);
        }
        for(char c : t.toCharArray()){
            if(map.containsKey(c)) map.put(c , map.get(c) -1 );
            else return c;
        }
        for (char c : t.toCharArray()){
            if(map.get(c) != 0) return c;
        }
        return ' ';
    }
    /**
     * one line solution
     * Runtime: 37 ms, faster than 5.29% of Java online submissions for Find the Difference.
     * Memory Usage: 34.7 MB, less than 99.58% of Java online submissions for Find the Difference.
     */
    public char findTheDifference2(String s , String t){
        return (char)(s+t).chars().reduce((l, r) -> l^r).getAsInt();
    }
    /**
     * great idea : XOR
     * Runtime: 1 ms, faster than 99.70% of Java online submissions for Find the Difference.
     * Memory Usage: 37.4 MB, less than 64.70% of Java online submissions for Find the Difference.
     */
    public char findTheDifference3(String s, String t) {
        char xor = 0;

        for (char c: s.toCharArray()) {
            xor ^= c;
        }

        for (char c: t.toCharArray()) {
            xor ^= c;
        }

        return xor;
    }
}
public class No389findTheDifference {
    public static void main(String[] args){
        String s = "abcd";
        String t = "abcdd";
        System.out.println(new Solution389().findTheDifference(s , t));
    }
}
